Task {
    shape : class

    -id
    -item
    -status
    -createdDate
}

TaskRepository

MainController {
    shape : class

    -taskService
    list()
    
}

TaskService {
    shape : class

    -taskRepository
    getList()
}