getrequest: {
  shape: sequence_diagram

  th: Thymeleaf
  con: MainController
  ser: TaskService
  re: TaskRepository
  get(list): {
    con -> ser: getList()
    ser -> re : findAll()
    re -> ser 
    ser -> con: taskList
    con -> th: model+taskList
  }
}
